kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:image-puller-dev"
  namespace: b07b69-tools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b07b69-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-puller"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:image-puller-test"
  namespace: b07b69-tools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b07b69-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-puller"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:image-puller-prod"
  namespace: b07b69-tools
subjects:
  - kind: ServiceAccount
    name: default
    namespace: b07b69-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:image-puller"
